# -*- coding: utf-8 -*-
"""dataloader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import yfinance as yf
import pandas as pd

def fetch_stock_data(ticker="AAPL", start="2020-01-01", end="2024-12-31"):
    df = yf.download(ticker, start=start, end=end)
    df = df[["Open", "High", "Low", "Close", "Volume"]]
    df.dropna(inplace=True)
    return df