# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import pandas as pd
import ta

def add_technical_indicators(df):
    df = df.copy()
    df = ta.add_all_ta_features(
        df, open="Open", high="High", low="Low", close="Close", volume="Volume", fillna=True
    )
    df = df.dropna()
    return df