# -*- coding: utf-8 -*-
"""hybrid_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import torch
import torch.nn as nn
from tcn_model import TCN
from transformer_model import TransformerModel

class HybridTCNTransformer(nn.Module):
    def __init__(self, input_dim, tcn_channels, transformer_dim, num_heads, num_layers, dropout=0.1):
        super().__init__()
        self.tcn = TCN(input_size=input_dim, output_size=transformer_dim, num_channels=tcn_channels, dropout=dropout)
        self.transformer = TransformerModel(input_dim=transformer_dim, model_dim=transformer_dim,
                                            num_heads=num_heads, num_layers=num_layers, dropout=dropout)

    def forward(self, x):
        # x: [batch, seq_len, input_dim]
        tcn_out = self.tcn(x)  # [batch, transformer_dim]
        tcn_out = tcn_out.unsqueeze(1).repeat(1, x.size(1), 1)  # [batch, seq_len, transformer_dim]
        return self.transformer(tcn_out)