# -*- coding: utf-8 -*-
"""streamlitapp.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import streamlit as st
import torch
import numpy as np
import matplotlib.pyplot as plt
from hybrid_model import HybridTCNTransformer

# Model config (same as training)
input_dim = 10
tcn_channels = [32, 64]
transformer_dim = 64
num_heads = 4
num_layers = 2
dropout = 0.1

# Load trained model
device = torch.device("cpu")
model = HybridTCNTransformer(input_dim, tcn_channels, transformer_dim, num_heads, num_layers, dropout)
model.load_state_dict(torch.load("hybrid_model.pth", map_location=device))
model.eval()

st.title("📈 Stock Price Prediction - TCN + Transformer")

st.markdown("Upload preprocessed input data or use simulated values.")
seq_len = 60

# Simulate input data
if st.button("Use Random Sample Input"):
    x = np.random.randn(1, seq_len, input_dim).astype(np.float32)
    with torch.no_grad():
        y_pred = model(torch.tensor(x))
    st.success(f"📊 Predicted stock value: **{y_pred.item():.4f}**")

    # Plot
    st.subheader("Input Feature Snapshot")
    fig, ax = plt.subplots()
    ax.plot(x[0][:, 0], label="Feature 1")
    ax.plot(x[0][:, 1], label="Feature 2")
    ax.legend()
    st.pyplot(fig)

# Optional: Upload input data
st.markdown("---")
uploaded_file = st.file_uploader("Upload .npy file containing input data (shape: [1, 60, 10])", type="npy")
if uploaded_file is not None:
    x = np.load(uploaded_file).astype(np.float32)
    if x.shape != (1, seq_len, input_dim):
        st.error(f"Expected shape (1, {seq_len}, {input_dim}), got {x.shape}")
    else:
        with torch.no_grad():
            y_pred = model(torch.tensor(x))
        st.success(f"📊 Predicted stock value: **{y_pred.item():.4f}**")