# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import torch
import torch.nn as nn
import torch.optim as optim
from hybrid_model import HybridTCNTransformer

# Dummy dataset
def generate_synthetic_data(samples=1000, seq_len=60, features=10):
    X = torch.randn(samples, seq_len, features)
    y = torch.randn(samples, 1)  # regression target
    return X, y

# Hyperparameters
input_dim = 10
tcn_channels = [32, 64]
transformer_dim = 64
num_heads = 4
num_layers = 2
dropout = 0.1
epochs = 10
batch_size = 32
lr = 0.001

# Dataset
X, y = generate_synthetic_data()
dataset = torch.utils.data.TensorDataset(X, y)
loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridTCNTransformer(input_dim, tcn_channels, transformer_dim, num_heads, num_layers, dropout).to(device)

# Loss & Optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=lr)

# Training loop
print("Starting training...")
for epoch in range(epochs):
    total_loss = 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        preds = model(xb)
        loss = criterion(preds, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss / len(loader):.4f}")

# Save the model
torch.save(model.state_dict(), "hybrid_model.pth")
print("Model saved to hybrid_model.pth")