# -*- coding: utf-8 -*-
"""transformer_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ODGbnUs_9_N1yYSMWgVk-mRBrctVU-
"""

import torch
import torch.nn as nn

class TransformerModel(nn.Module):
    def __init__(self, input_dim, model_dim, num_heads, num_layers, dropout=0.1):
        super().__init__()
        self.embedding = nn.Linear(input_dim, model_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=model_dim, nhead=num_heads, dropout=dropout)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc_out = nn.Linear(model_dim, 1)

    def forward(self, x):
        # x: [batch, seq_len, input_dim]
        x = self.embedding(x)  # [batch, seq_len, model_dim]
        x = x.permute(1, 0, 2)  # [seq_len, batch, model_dim] for Transformer
        x = self.transformer_encoder(x)
        x = x[-1]  # last time step
        return self.fc_out(x)